import type { ComponentType } from 'react';
import {
  BowlIcon,
  CelloIcon,
  ChimesIcon,
  FanIcon,
  FluteIcon,
  FlameIcon,
  KeysIcon,
  LeafIcon,
  MoonIcon,
  RainIcon,
  RiverIcon,
  StormIcon,
  TreesIcon,
  WaveIcon,
  WindIcon,
} from '../../components/icons/Icons';

export const soundIcons: Record<string, ComponentType<{ size?: number }>> = {
  rain: RainIcon,
  storm: StormIcon,
  river: RiverIcon,
  wave: WaveIcon,
  trees: TreesIcon,
  flame: FlameIcon,
  wind: WindIcon,
  keys: KeysIcon,
  leaf: LeafIcon,
  moon: MoonIcon,
  chimes: ChimesIcon,
  fan: FanIcon,
  flute: FluteIcon,
  cello: CelloIcon,
  bowl: BowlIcon,
};
